# Generated by Django 5.2.8 on 2025-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_research_created_at_research_image_research_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
