# Generated by Django 5.2.8 on 2025-12-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, to='portfolio.skill'),
        ),
    ]
