# Generated by Django 5.2.8 on 2025-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_research_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Uncheck if this is just a project tag'),
        ),
    ]
