# Generated by Django 5.2.8 on 2025-12-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_profile_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_background',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
    ]
