# Generated by Django 5.2.8 on 2025-12-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume',
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_de',
            field=models.FileField(blank=True, null=True, upload_to='resume/de/', verbose_name='Resume (German)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_en',
            field=models.FileField(blank=True, null=True, upload_to='resume/en/', verbose_name='Resume (English)'),
        ),
    ]
