# Generated by Django 5.2.8 on 2025-12-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_profile_resume_profile_resume_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_images', to='portfolio.profile')),
            ],
        ),
    ]
