# Generated by Django 5.2.8 on 2025-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_aboutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='published_in',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
