# Generated by Django 5.2.8 on 2025-12-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_research_published_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
