# Generated by Django 5.2.8 on 2025-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_experience_company_logo_experience_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='academic_projects/')),
                ('github_link', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_stack', models.ManyToManyField(blank=True, to='portfolio.skill')),
            ],
        ),
    ]
